apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: myapp
        image: 040872219986.dkr.ecr.us-east-1.amazonaws.com/my-ecr-mr:latest
        ports:
        - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: "webapp-myapp-svc"             #name of service
spec:                               #service and pod connection properties
  selector:                         #the selector value of service should match with pod "Label"
    env: dev                    #key and value
  ports:
    - protocol: "TCP"                   #TCP, UDP, TLS
      port: 8080
      targetPort: 8080
  type: LoadBalancer 
